# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 529)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setObjectName("btnSalvar")
        self.gridLayout.addWidget(self.btnSalvar, 7, 1, 1, 1)
        self.btnDeletar = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeletar.setObjectName("btnDeletar")
        self.gridLayout.addWidget(self.btnDeletar, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 3)
        self.btnCarregarMarcadores = QtWidgets.QPushButton(self.centralwidget)
        self.btnCarregarMarcadores.setObjectName("btnCarregarMarcadores")
        self.gridLayout.addWidget(self.btnCarregarMarcadores, 3, 2, 1, 1)
        self.LabelMarc = QtWidgets.QTextEdit(self.centralwidget)
        self.LabelMarc.setObjectName("LabelMarc")
        self.gridLayout.addWidget(self.LabelMarc, 2, 0, 1, 3)
        self.labelAreas = QtWidgets.QTextEdit(self.centralwidget)
        self.labelAreas.setObjectName("labelAreas")
        self.gridLayout.addWidget(self.labelAreas, 5, 0, 1, 3)
        self.btnIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIniciar.setObjectName("btnIniciar")
        self.gridLayout.addWidget(self.btnIniciar, 7, 2, 1, 1)
        self.btnCarregarAreas = QtWidgets.QPushButton(self.centralwidget)
        self.btnCarregarAreas.setObjectName("btnCarregarAreas")
        self.gridLayout.addWidget(self.btnCarregarAreas, 6, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 6, 0, 1, 1)
        self.btnReload = QtWidgets.QPushButton(self.centralwidget)
        self.btnReload.setObjectName("btnReload")
        self.gridLayout.addWidget(self.btnReload, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agrupador Pro"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar"))
        self.btnDeletar.setText(_translate("MainWindow", "Deletar"))
        self.label_2.setText(_translate("MainWindow", "Areas"))
        self.label.setText(_translate("MainWindow", "Marcadores"))
        self.btnCarregarMarcadores.setText(_translate("MainWindow", "Carregar"))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.btnCarregarAreas.setText(_translate("MainWindow", "Carregar"))
        self.checkBox.setText(_translate("MainWindow", "Salvar por Areas"))
        self.btnReload.setText(_translate("MainWindow", "Limpar"))
